version: 2
jobs:
  build:
      working_directory: ~/ngx-facebook/
      docker:
        - image: circleci/node:8-browsers
      steps:
        - checkout
           name: Install node modules
           command: npm i
        - run:
           name: Lint
           command: npm run lint
        - run:
           name: Build module
           command: npm run build
        - run:
           name: Test
           command: npm test
